---

run:
  tests: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - ireturn
    - depguard
    - exhaustivestruct
    - exhaustruct
    - exhaustive
    - wsl
    - gochecknoinits
    - funlen
    - gocognit
    - cyclop
    - forbidigo
    - nosnakecase
linters-settings:
  gosec:
    excludes:
      - G402 # We allow InsecureSkipVerify in our code