---

run:
  tests: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - ireturn
    - depguard
    - exhaustivestruct
    - exhaustruct
    - exhaustive
    - wsl
    - gochecknoinits
    - funlen
    - gocognit
    - cyclop