---

# Enable verbose logging
verbose: false

# Redfish Default Credentials
redfish:
  verifyTls: true
  username: Administrator
  password: toor

# Actions to perform before collecting metrics
preActions:
  - reset_intrusion_alert