name: linting

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Install dependencies
        run: go mod download
      - name: Linting code
        uses: golangci/golangci-lint-action@v4
      - name: Running tests
        run: go test ./...
