name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: go-semantic-release/action@v1
        id: rel
        with:
          hooks: goreleaser
          github-token: ${{ github.token }}
          changelog-generator-opt: "emojis=true"
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        if: steps.rel.outputs.version != ''
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: gportal/redfish_exporter:latest,gportal/redfish_exporter:${{ steps.rel.outputs.version }}
